import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useSigner, useContract, useAccount } from "wagmi";
import { CONTRACT_ADDRESS, CONTRACT_ABI } from "../constants/index";
import { useEffect, useState } from "react";
import { ethers } from "ethers";
import { create } from "ipfs-http-client";
const client = create("https://ipfs.infura.io:5001/api/v0");

export default function Home() {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const contract = useContract({
    addressOrName: CONTRACT_ADDRESS,
    contractInterface: CONTRACT_ABI,
    signerOrProvider: signer,
  });

  const [isOwner, setIsOwner] = useState(false);
  const [isRegistered, setIsRegistered] = useState(false);
  const [isVerified, setIsVerified] = useState(false);
  const [_address, _setAddress] = useState("");
  const [myProfile, setMyProfile] = useState("");
  const [name, setName] = useState("");
  const [file, setFile] = useState("");
  const [imgURL, setImageURL] = useState("");
  const [email, setEmail] = useState("");
  const [aadhaar, setAadhaar] = useState("");
  const [pan, setPan] = useState("");

  const verification = async () => {
    try {
      console.log("hi");
      if (email && aadhaar && pan && file) {
        const added = await client.add(file);
        const url = `https://ipfs.infura.io/ipfs/${added.path}`;
        setImageURL(url);
        console.log(url);
        const txn = await contract.addProfile(email, aadhaar, pan, added.path);
        console.log("Loading...")
        await txn.wait();
        console.log("completed")
      }
    } catch (error) {
      console.log(error);
    }
  };

  const register = async () => {
    try {
      if (name) {
        const txn = await contract.register(name);
        console.log("Loading...")
        await txn.wait();
        console.log("completed")
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getProfile = async () => {
    try {
      if (ethers.utils.isAddress(_address)) {
        const profile = await contract.digitalIdentities(_address);
        console.log(profile);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getMyProfile = async () => {
    try {
      const profile = await contract.profiles(address);
      console.log(profile);
      setMyProfile(profile);
    } catch (error) {
      console.log(error);
    }
  };

  const getRegistration = async () => {
    try {
      const status = await contract.registered(address);
      console.log(status);
      if (status === true) {
        setIsRegistered(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getVerification = async () => {
    try {
      const status = await contract.verified(address);
      console.log(status);
      if (status === true) {
        setIsVerified(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getOwner = async () => {
    try {
      const owner = await contract.owner();
      if (owner.toLowerCase() === address.toLowerCase()) {
        setIsOwner(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    // if (ethers.utils.isAddress(address)) {
    //   getOwner();
    //   getRegistration();
    //   getVerification();
    //   getMyProfile();
    // }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Verifiable Credentials</a>
        </h1>
        <ConnectButton />
        <div className={styles.grid}>
          <div className={styles.card}>
            <h3>Get Profile</h3>
            <input
              type="text"
              placeholder="enter address"
              onChange={(e) => {
                _setAddress(e.target.value);
              }}
            />
            <button onClick={getProfile}>Get</button>
          </div>
          <div className={styles.card}>
            <h3>Get a an idetity</h3>
            <input
              type="text"
              placeholder="enter name"
              onChange={(e) => {
                setName(e.target.value);
              }}
            />
            <button onClick={register}>Get a DID</button>
          </div>
          <div className={styles.card}>
            <h3>Verified Credentials</h3>
            <div>
              <input
                type="email"
                placeholder="email"
                onChange={(e) => {
                  setEmail(e.target.value);
                  e.preventDefault();
                }}
              />
              <input
                type="text"
                placeholder="aadhaar"
                onChange={(e) => {
                  setAadhaar(e.target.value);
                  e.preventDefault();
                }}
              />
              <input
                type="text"
                placeholder="pan"
                onChange={(e) => {
                  setPan(e.target.value);
                  e.preventDefault();
                }}
              />
              <input
                type="file"
                placeholder="driving license"
                onChange={(e) => {
                  setFile(e.target.files[0]);
                  e.preventDefault();
                }}
                style={{ width: "300px" }}
              />
              <button onClick={verification}>Veify your identity</button>
            </div>
          </div>
          <div className={styles.card}>
            <p>Verified</p>
            {myProfile}
          </div>
        </div>
      </main>
    </div>
  );
}
