import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useSigner, useContract, useAccount } from "wagmi";
import { CONTRACT_ADDRESS, CONTRACT_ABI } from "../constants/index";
import { useEffect, useState } from "react";
import { ethers } from "ethers";

export default function Home() {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const contract = useContract({
    addressOrName: CONTRACT_ADDRESS,
    contractInterface: CONTRACT_ABI,
    signerOrProvider: signer,
  });

  const [isOwner, setIsOwner] = useState(false);
  const [isRegistered, setIsRegistered] = useState(false);
  const [isVerified, setIsVerified] = useState(false);
  const [_address, _setAddress] = useState();
  const [myProfile, setMyProfile] = useState();
  const [name, setName] = useState();

  const register = async () => {
    try {
      if (name) {
        await contract.register(name);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getProfile = async () => {
    try {
      if (ethers.utils.isAddress(_address)) {
        const profile = await contract.digitalIdentities(_address);
        console.log(profile);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getMyProfile = async () => {
    try {
      const profile = await contract.profiles(address);
      console.log(profile);
      setMyProfile(profile);
    } catch (error) {
      console.log(error);
    }
  };

  const getRegistration = async () => {
    try {
      const status = await contract.registered(address);
      console.log(status);
      if (status === true) {
        setIsRegistered(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getVerification = async () => {
    try {
      const status = await contract.verified(address);
      console.log(status);
      if (status === true) {
        setIsVerified(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const getOwner = async () => {
    try {
      const owner = await contract.owner();
      if (owner.toLowerCase() === address.toLowerCase()) {
        setIsOwner(true);
      }
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    if (ethers.utils.isAddress(address)) {
      getOwner();
      getRegistration();
      getVerification();
      getMyProfile();
    }
  }, []);

  function renderButton() {
    if (address && !isRegistered) {
      return (
        <div className={styles.card}>
          <h3>Get a an idetity</h3>
          <input type="text" placeholder="enter your address" onChange={(e)=>{setName(e.target.value)}} />
          <button onClick={register}>Get a DID</button>
        </div>
      );
    }
    if (address && isRegistered && !isVerified) {
      return (
        <div className={styles.card}>
          <h3>Verified Credentials</h3>
          <div>
            <input type="email" placeholder="email" />
            <input type="text" placeholder="aadhaar" />
            <input type="text" placeholder="pan" />
            <input type="file" placeholder="driving license" />
            <button>Veify your identity</button>
          </div>
        </div>
      );
    }
    if (address && isRegistered && isVerified) {
      return (
        <div>
          <p>Verified</p>
          {myProfile}
        </div>
      );
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Verifiable Credentials</a>
        </h1>
        <ConnectButton />
        <div className={styles.grid}>
          <div className={styles.card}>
            <h3>Get Profile</h3>
            <input
              type="text"
              placeholder="enter address"
              onChange={(e) => {
                _setAddress(e.target.value);
              }}
            />
            <button onClick={getProfile}>Get</button>
          </div>
          {renderButton()}
        </div>
      </main>
    </div>
  );
}
